### ISSUE TITLE
add orientation widget

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#45]
this is useful to know the current scene is oriented in the RAS space.

we need an extra renderer.
http://jsfiddle.net/aqnL1mx9/

on hover any of the elements, show a nice css overlay to tell us if this is R, A or S?
(will be useful later on for other widget.)

**Comment by NicolasRannou** [comment]
First version implemented:
http://fnndsc.github.io/vjs/#widgets_orientation

@rudolphpienaar @jbernal0019 @pieper: I got confused yesterday:

The blue box is a bounding box for the presented data, purely aligned in the RAS space. As an abstraction, we can think of it as the head of the patient.

The cyan box is the oriented bounding box of the actual data, within the "abstract head" of the patient.

At the bottom right, you will notice a new widget. It helps us to get oriented in this RAS space:
R: red axis
A: green axis
S: blue axis

So far, the whole scene is presented in RAS space. We should discuss it next week. The assumption is that when we provide a volume to be displayed, we also provide a IJKToRAS transform for this volume if we want to orient it properly.

We should add another transform to display the Scene in a World Coordinate system rather RAS. Assuming as we can get this transform from dcm, nii, mgz, nrrd it should be straight forward and tackled ASAP!

@pieper: Do you know if Slicer uses the World or RAS space as its common space to ensure everything is properly aligned/oriented?

**Comment by NicolasRannou** [comment]
Closed by https://github.com/FNNDSC/vjs/commit/d8b0aecc733b3a7d1e521ed14624cd91ea041489

**Comment by pieper** [comment]
Hi Nicolas - 

Yes, in Slicer RAS is World space.  

As a general rule, we should keep in mind that 'everything is relative'.  So even though we may pick an origin measurement frame it is arbitrary.  

In DICOM there is the concept of FrameOfReferenceUID (or just FoR) so that any coordinates or orientations (such as ImagePosition and ImageOrientation which define IJKToRAS) that share the same FoR are known to be in the same space.  

A RegistrationObject in DICOM is a mapping from one FoR to another FoR.

Generating an image is a matter of picking a sampling grid in a particular FoR (i.e. pixel space on the screen) and then mapping backwards through registration transforms and image positions/orientation information to sample acquisition pixel data.

We can discuss more details next week.

-Steve

**Comment by NicolasRannou** [comment]
Interesting, I am not familiar with the FrameOfReferenceUID but it makes sense, I'll look into it.

I'll walk you through the approach currently used to generate the image on Thursday but basically we map [pixel on the screen] -> [sample acquisition pixel data] directly in the fragment shader. The only trick is to pass the RASToIJK transform to the shaders, along with all the raw data. ThreeJS provides convenience transforms to map screen position to RAS coordinate directly in the shaders.

-Nicolas
