### ISSUE TITLE
Embed New Viewer in ChRIS Feed

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#60]
# New Visual Panel in ChRIS Feed

@jbernal0019 @NicolasRannou 
## Requirement
- Add a new "panel" to the ChRIS feed called "Visual". This panel will contain an embedded "viewer" rooted on the main feed directory.
## Things to consider
- Back end / server side processing. If the feed directory contains NIfTI data, jpg thumbnails have to be generated: likewise for DICOM data.
- Size, depth of tree. How deep do we recurse? If someone creates a feed on the root of the whole filesystem, i.e. <tt>/</tt> (!!) then the viewer shouldn't scan over the entire filesystem!

**Comment by rudolphpienaar** [comment]
Just going to bump up the priority of this...

**Comment by NicolasRannou** [comment]
First approach tested is to add plugin-specific viewers:

Logic:
1- Run pacs pull as usually
2- Add a step at the end of pacs_pull plugin: add index.html in feed directory.
3- When create, the feed will detect this index.html and embed it in an iframe.

Have and external html allows to decouple the viewer from everything else, which is nice.
index.html represents the "pacs_pull viewer" (mi2b2 viewer to start).

Work in progress @chris/nicolas

Notes:
1- JPEGS are generated by the dicom listener.
2- json object might need a new "jpeg" field
3- memmory issues considerations later: can not load everything at once: need urls rather than objects?

**Comment by NicolasRannou** [comment]
First version of integrated mi2b2 viewer in pacs_pull feeds implemented. Looks like it could work.
Feedback?

Do a pacs_pull on chris/nicolas
Then load data in the viewer to have a feeling of what it would look like.

Of course it will need a specialized viewer, not the mi2b2 viewer ultimately.
